name: build menuconfig

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install deps and build
      run: |
        sudo chmod 777 ./install_deps.sh
        bash ./install_deps.sh
        mkdir build && cd build && cmake .. && make menuconfig
